accounts/urls.py
from django.urls import path
from .views import *


app_name = 'accounts'


urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]


urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from .views import *


app_name = 'todo'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('delete/<int:pk>', DeleteTask.as_view(), name='delete_task'),
    path('complete/<int:pk>', CompleteTask.as_view(), name='complete_task'),
    path('update/<int:pk>', UpdateTask.as_view(), name='update_task'),
]

accounts/models.py
from django.db import models

from django.db import models
from django.contrib.auth.models import AbstractUser, AbstractBaseUser,BaseUserManager,PermissionsMixin



class CustomeBaseUserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user
    
    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self.create_user(email, password, **extra_fields)



class CustomeUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    username  = models.CharField(max_length=100, unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomeBaseUserManager()

    def __str__(self):
        return self.email

todo/models.py
from django.db import models
from accounts.models import CustomeUser

class Task(models.Model):
    user = models.ForeignKey(CustomeUser,on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    complete = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomeUser



class CustomUserCreation(UserCreationForm):



    class Meta:
        model = CustomeUser
        fields = [ 'email','username', 'password1', 'password2']




class AuthenticationForm(forms.Form):
    """
    Base class for authenticating users. Extend this to get a form that accepts
    username/password logins.
    """

    email = forms.EmailField()
    password = forms.CharField(
        label=("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password"}),
    )

todo/forms.py
from django import forms
from .models import Task


class UpdateTask(forms.Form):
    title = forms.CharField(max_length=255)


class CreateTaskForm(forms.ModelForm):
    
    class Meta:
        model = Task
        fields = ('title', )

accounts/views.py
from django.shortcuts import redirect
from .forms import CustomUserCreation
from django.contrib.auth import authenticate, login, logout
from .forms import AuthenticationForm
from django.views.generic import FormView, CreateView, TemplateView


class LoginView(FormView):
     template_name = 'registration/login.html'
     form_class = AuthenticationForm
     success_url = '/'
     def form_valid(self, form):
         email = self.request.POST.get('email')
         password = self.request.POST.get('password')
         user = authenticate(email=email)
         if user is not None:
              login(self.request, user)
              return super().form_valid(form)
         


class LogOutView(TemplateView):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('/')



class SignUpView(CreateView):
     template_name = 'registrations/signup.html'
     form_class = CustomUserCreation
     success_url = '/accounts/login/'

todo/views.py
from django.shortcuts import get_object_or_404, redirect
from accounts.models import CustomeUser
from django.views.generic import ListView, UpdateView, DeleteView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Task
from .forms import CreateTaskForm



class HomeView(LoginRequiredMixin, ListView):
    template_name = 'todo/index.html'
    context_object_name = 'tasks'
    
    def get_queryset(self):
        pass

    
    def post(self, request, *args, **kwargs):
        pass




class DeleteTask(DeleteView):
    model = Task
    success_url = '/'





class CompleteTask(LoginRequiredMixin, View):
    pass



class UpdateTask(UpdateView):
    model = Task
    template_name = 'todo/update_task.html'
    fields = ['title']
    success_url = '/'
    context_object_name = 'task'

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Ali Bigdeli">
    <meta name="generator" content="Hugo 0.88.1">
    <title>{% block title %} {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <style>
        body {
            width: 100%;
            height: 100vh;            
            background: linear-gradient(to bottom, #e6e6e6 0%, #ffffff 100%);
        }
    </style>
    {% block extra_css %}{% endblock %}
</head>

<body>
    {% block content %}{% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>
    {% block extra_js %}{% endblock %}
</body>

</html>

templates/base_auth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block title %}{% endblock title %}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href={% static "images/icons/favicon.ico" %}/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static "vendor/bootstrap/css/bootstrap.min.css" %}>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static "fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static "vendor/animate/animate.css" %}>
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href={% static "vendor/css-hamburgers/hamburgers.min.css" %}>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static "vendor/select2/select2.min.css" %}>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static "css/util.css" %}>
	<link rel="stylesheet" type="text/css" href={% static "css/main.css" %}>
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src={% static "images/img-01.png" %} alt="IMG">
				</div>
{% block content %}
{% endblock content %}
	
	

	
<!--===============================================================================================-->	
<script src={% static "vendor/jquery/jquery-3.2.1.min.js" %}></script>
<!--===============================================================================================-->
	<script src={% static "vendor/bootstrap/js/popper.js" %}></script>
	<script src={% static "vendor/bootstrap/js/bootstrap.min.js" %}></script>
<!--===============================================================================================-->
	<script src={% static "vendor/select2/select2.min.js" %}></script>
<!--===============================================================================================-->
	<script src={% static "vendor/tilt/tilt.jquery.min.js" %}></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src={% static "js/main.js" %}></script>

</body>
</html>

templates/todo/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Todo List {% endblock %}
{% block extra_css %}{% endblock %}

{% block content %}
<div class="container">
  <p>loged as {{request.user.email}}</p>
  <p><a href={% url 'password_change' %}>change password</a></p>
  <p><a href={% url 'accounts:logout' %}>logout</a></p>
</div>
<div class="modal modal-signin position-static d-block  py-5" tabindex="-1" role="dialog" id="modalSignin">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-5 shadow">
      <div class="modal-header p-5 pb-4 border-bottom-0">

        <h2 class="fw-bold mb-0">Todo App</h2>
        <a type="button" class="btn-close" href="{% url 'accounts:logout' %}"></a>
      </div>

      <div class="modal-body p-5 pt-0">

        <form class="pt-3" method="POST" >
          {% csrf_token %}
          <div class="input-group mb-3">
            <input type="text" class="form-control rounded-4" name="title" placeholder="Enter task title"
              aria-label="Recipient's username" aria-describedby="button-addon2">
            <button class="btn btn-primary" type="submit">Add</button>
          </div>
        </form>
          <hr class="my-4">
          {% for task in tasks %}
          <div class="input-group py-1">
            <span type="text" class="form-control" aria-label="Text input with segmented dropdown button">
              {% if task.complete == True %}
              <strike>{{task.title}}</strike>
              {% else %}
              <span>{{task}}</span>
              {% endif %}
            </span>
            <a type="button" class="btn btn-danger" href="{% url 'todo:delete_task' pk=task.id %}"><i class="bi bi-trash"></i></a>
            <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown"
              aria-expanded="false">
              <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><a class="dropdown-item" href="{% url 'todo:complete_task' pk=task.id %}">Done</a></li>
              <li><a class="dropdown-item" href={% url 'todo:update_task' pk=task.id %}>Edit</a></li>
            </ul>
          </div>
      
          {% endfor %}          
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base_auth.html" %}
{% block title %}Login{% endblock title %}Login 
{% block content %}
<form class="login100-form validate-form" method="post">
    {% csrf_token %}
    <span class="login100-form-title">
        Are you sure you want to delete tasks?
    </span>
    <div class="container-login100-form-btn">
        <button class="login100-form-btn">
            Delete Task
        </button>
    </div>
</form>
</div>
</div>
</div>
{% endblock content %}

templates/todo/update_task.html
{% extends "base_auth.html" %}
{% block title %}Login{% endblock title %}Login 
{% block content %}
<form class="login100-form validate-form" method="post">
    {% csrf_token %}
    <span class="login100-form-title">
        Edit Task
    </span>

    <div class="wrap-input100 validate-input">
        <input class="input100" type="text" name="title" placeholder="new title">
        <span class="focus-input100"></span>
        <span class="symbol-input100">
            <i class="fa fa-envelope" aria-hidden="true"></i>
        </span>
    </div>
    <div class="container-login100-form-btn">
        <button class="login100-form-btn">
            Edit title
        </button>
    </div>
</form>
</div>
</div>
</div>
{% endblock content %}